// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVpdGqbpX_pqpt2GYbpfRSRccxNjMIHFk',
    appId: '1:907286443175:web:8e3d09eda4a93',
    messagingSenderId: '907286443175',
    projectId: 'hostel-app-3afa1',
    authDomain: 'hostel-app-3afa1.firebaseapp.com',
    storageBucket: 'hostel-app-3afa1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVpdGqbpX_pqpt2GYbpfRSRccxNjMIHFk',
    appId: '1:907286443175:android:7a60c2b1d7652059e09782',
    messagingSenderId: '907286443175',
    projectId: 'hostel-app-3afa1',
    storageBucket: 'hostel-app-3afa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEnXPOJwzkYWsbR0UJupBDNfrcHN-vgI',
    appId: '1:907286443175:ios:9eaf736b4690bcf0e09782',
    messagingSenderId: '907286443175',
    projectId: 'hostel-app-3afa1',
    storageBucket: 'hostel-app-3afa1.firebasestorage.app',
    iosBundleId: 'com.vianasoft.vianastay',
  );
}
